import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const IS_DEV = process.env.NODE_ENV === 'development';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, 'flex flex-col')}
        suppressHydrationWarning={IS_DEV}
      >
        <nav className="bg-gray-800 grow-0">
          <ul
            className="mx-auto w-full max-w-2xl h-16 flex space-x-4 justify-center items-center"
          >
            <li className="mr-auto">
              <Link href="/">home</Link>
            </li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
            <li>
              <Link href="/posts/create">New post</Link>
            </li>
          </ul>
        </nav>
        <main className="flex flex-col mx-auto grow w-full max-w-2xl pt-4 format format-sm sm:format-base lg:format-lg">
          {children}
        </main>
      </body>
    </html>
  );
}
