import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const IS_DEV = process.env.NODE_ENV === 'development';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, 'flex flex-col')}
        suppressHydrationWarning={IS_DEV}
      >
        <nav className="grow-0 bg-gray-800">
          <ul className="mx-auto flex h-16 w-full max-w-2xl items-center justify-center space-x-4">
            <li className="mr-auto">
              <Link href="/">home</Link>
            </li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
            <li>
              <Link href="/posts/create">New post</Link>
            </li>
          </ul>
        </nav>
        <main className="format format-sm sm:format-base lg:format-lg mx-auto flex w-full max-w-2xl grow flex-col pt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
